### ISSUE TITLE
Search Decode Issue

### ISSUE THREAD

**Issue by GRMrGecko** [z411/trackma#104]
I get this issue when I search AniList for a specific show https://gist.github.com/GRMrGecko/7a95dc1db09a06f3a9a1

**Comment by z411** [comment]
This is because the server is returning an empty document when there are no results; I fixed it to handle it properly.

Still, it's not an encoding issue, but merely not getting any results. It seems this anime exists in the database with a different name.
http://anilist.co/anime/20813
If I only search for "Bonjour" or "Bonjour Sweet Love" in the site (or in Trackma) I don't get results either, since "BONJOUR♪Sweet" is a single word. You might want to request a change of alias as to separate those words.

**Comment by Argon-** [comment]
(or a better search engine)

**Comment by z411** [comment]
Certainly. Anilist is under development so this case can act as a good suggestion to improve the search engine.
