### ISSUE TITLE
User hooks

### ISSUE THREAD

**Issue by rr-** [z411/trackma#117]
Right now I use a shell script wrapper for mpv that logs what I watched somewhere.
It would be nicer, however, if we could issue any user command whenever the episode count is actually updated:

1. If I open a video just for a second, my script detects it as a false positive and I need to ssh into the server, open the log and remove the line.
2. I could try looking at timestamps, but that's what Trackma already does, and Trackma is more superior at this.
3. I still have a problem if my player autoloads next episode - my script won't detect it, while Trackma will.

These are of course issues with my script, not Trackma, but it shows how easier it would be on users if they had such a feature.

**Comment by z411** [comment]
That sounds good; it could also be useful for people who want to post things to Twitter or HTTP or whatever with a shell script.

I'm not sure if this should be implemented in the tracker or the data manager itself.
If it's implemented in the former, it would call the script only when the episode is updated automatically by the media tracker (note that Play Next is not part of the tracker).
If it's implemented in the latter, it would call the script when the user updates it manually *and* when it's updated automatically by the tracker.
What do you think?

**Comment by rr-** [comment]
To me it makes more sense to make it update in both cases.

**Comment by kazuoteramoto** [comment]
I love to see this in trackma, as now I just edit the `update_watched` to do
something like the OP (but in my case I move the files around).

I love how https://github.com/pazz/alot (an email client) works in this aspect.

It have a hook system that call user defined python function like
`pre_updated_watched` or `post_updated_watched`, they are defined in a hook.py
file. The relevant alot doc is
https://alot.readthedocs.org/en/latest/configuration/hooks.html

A lot of the `get_/set_/update_/delete_/add_` make sense of getting this
treatment. The advantage, in my opinion, is that you leave part of the
complexity to the end user and reduce the user case scenarios you need to
cover.

At start the signature can be just the same parameters the parent functions
get.

**Comment by z411** [comment]
That sounds interesting, but it's little bit different from what OP is asking, which is calling an external process. I think an external command is more user friendly as any relatively knowledgeable user can input a command with arguments in the settings window, while hooks would only benefit people with Python knowledge.

**Comment by z411** [comment]
So I've been thinking about @kazuoteramoto 's idea, and wouldn't it be better to have hooks for the signals (show_added, status_changed, etc) instead?

@rr- , what do you think of using hooks instead? Or would you still prefer configurable external commands? If so, I could implement both.

**Comment by rr-** [comment]
`hook.py` is perfectly fine with me.

**Comment by ToostInc** [comment]
Sorry for barging in, just been lurking till now because I like the idea.

Chiming in on the hooks idea, I've always like the [git-hooks](https://git-scm.com/book/it/v2/Customizing-Git-Git-Hooks) way of doing things: scripts in a folder hooks that will be executed based on their name(s), and given default inputs.

This is especially handy because it allows for code-independent hooks, a script could be written in bash just as easily as python, it just needs to parse the input right.

Shouldn't be much harder to implement than having a `hook.py` system either.

**Comment by kazuoteramoto** [comment]
The reason I sugested the alot hook system is because it don't need a good "plumbing" in place.

External commands and the git-hooks works great if you have a good way to interact and query infomation, like git plumbling commands.

In this way I like to think of the `hook.py` as something like using a internal plumbling system, with the noted disadvantage of no code-independent hooks.

Personally I also prefer a git-hook system with a good plumbling.

**Comment by rr-** [comment]
IMO a single Python `hook.py` is a little better than having multiple executables in separate hook directory, because it documents itself - compare example `hook.py`:

    def updated(account, episode):
        pass

with having an empty folder + lengthy documentation which file name gets what arguments. In the latter case, it is questionable where to put the documentation - trackma doesn't offer manpages, and embedding description for every possible hook command in README.md doesn't seem like a good idea. The first solution would require only a short notice in the README.md and the users would figure everything else out themselves by checking out single file.

**Comment by ToostInc** [comment]
Both your arguments have very good points! Documentation and ease of use are definitely important, but I think these issues can be resolved.

For ease of use should hooks are implemented either way, I think this will definitely become a power-user feature, rather than something the average user will use. 
I think the real deal-breaker between either method would then be: *do you know python?*
If you do, either method will work fine for you. If you don't; well you're kind of screwed with the `hooks.py` method.

For documentation, I obviously don't suggest we all put it in the README.md, which should always just be an overview of features, and install instructions. 
It'd be very easy though, to add some empty hook script examples; which would contain comment sections about when in the cycle the script is executed, and the input the script must handle. These could then be copied to `$install/hooks` or `/usr/share{/doc}/trackma` during install.
Similarly, we could just as simply maintain a /doc/HOOKS.md file, going into more detail and/or encourage users to send their own examples on what they have managed to do with hooks (this would be a suggestion of mine regardless of which method is finally implemented).

Lastly, small utility or not, when implementing a new feature I think it's always wise to implement it right, allowing for expansion where necessary. 
Not that the alot way does not necessarily allow for expansion, but you would see the single grow and grow in size as more hooks get added, and would eventually get too convoluted to be really useful.

This is of course not likely to happen in practice, but again, you never know for what purpose or in what way the code might be eventually used for.

**Comment by rr-** [comment]
I forgot about other thing - Python gives you more flexibility with regard to what arguments you pass to the hook user: you could pass binary image for the current anime etc. With shellscript oriented hooks, it might be cumbersome.

Either way, I don't have a strong opinion on either solution; I'm just thinking out loud about possible issues that others might consider important.

**Comment by z411** [comment]
Hi, I implemented a very basic hook system with a hook.py file in the user config folder where the signals (show_added, show_deleted, show_synced, etc.) call their respective hook if found.

This is a basic sample (`~/.trackma/hook.py`):
https://gist.github.com/z411/c41e343c5af2bfb23d22

It's primitive but it works. It should work for all signals defined in engine.py (including prompt_for_update and whatnot; they take the same arguments).
I should probably add ways to get more information (about the account or the mediatype, for example) and a way to send status messages back to Trackma.

**Comment by kazuoteramoto** [comment]
Nice, @z411 thanks for the commit. Can I sugest passing the `Engine()` object to the method? Something like this:
```diff
--- a/trackma/engine.py
+++ b/trackma/engine.py
@@ -146,7 +146,7 @@ class Engine:
             if self.hooks_available:
                 method = getattr(hook, signal)
                 self.msg.debug(self.name, "Calling hook %s..." % signal)
-                method(*args)
+                method(self, *args)
         except AttributeError:
             pass
 
-- 
```

`Engine()` has a lot of useful methods. With the above change I can easily implement my user case scenario (moving old files).
```python
import os

def get_old_episodes(engine, show):
    results = list()

    titles = engine.data_handler.get_show_titles(show)
    for ep in range(1, show['my_progress']+1):
        filename = engine._search_video(titles, ep)[0]
        if filename:
            results.append(filename)

    return results

def episode_changed(engine, show):
    for fname in get_old_episodes(engine, show):
        # move old watched episode to
        directory = os.path.join(engine.config['searchdir'], 'watched')
        if not os.path.exists(directory):
            os.makedirs(directory)
        os.rename(fname, os.path.join(directory, os.path.basename(fname)))
        # or remove old episode
        # os.unlink(fname)
```

**Comment by z411** [comment]
@kazuoteramoto Done.

Also added the example file in the docs directory.

**Comment by z411** [comment]
Here's another example that sends a Twitter update when a show is completed (python-twitter).
This way people can do external changes without cluttering Trackma's code. Thanks for the original suggestion.

https://gist.github.com/z411/fbcb86b528c90952cd64

I tried making a "Trackma" application on Twitter but the name was already taken, did anyone already try this?
