### ISSUE TITLE
Can't process a show

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#150]
* on MyAnimeList
* with trackma c2fddb280952fb0a893076b984487282438bea3c
* on a few very recent show (or unapproved show)

Exemple: On trackma, I've search the new kuroko movie to add it ; I can't sync with MyAnimeList
```
libmal: Adding show Kuroko no Basket Movie...
Data: Can't process Kuroko no Basket Movie, will leave unsynced.
Data: Info: Error adding: 501
```

The show in question is http://myanimelist.net/anime/31658 ; we can't find it by searching on the website http://myanimelist.net/anime.php?q=kuroko ; and the reason why we can't add it (and search it, even on the website) is because "This anime has not been approved yet.".

So, two solutions:
- let search it, but show that we can't add it (or throw an exception)
- hide it from the search

Thanks

**Comment by z411** [comment]
Hi, thanks for the heads up.

Sadly, looking at the output of the search API there doesn't seem to be a way to know beforehand if a show can be added or not (when searching for it, before adding it). That means that it doesn't seem possible to hide it from search results or disallow the user from adding it.

The only possible way from our side seems to be to let the user to add it to the local list, but just show the error as a warning when it attempts to sync (basically the same as now, but with a readable message rather than a 501 error). Looking at Taiga's behavior, a similar thing happens.
