### ISSUE TITLE
Rescanning library for plan to watch 

### ISSUE THREAD

**Issue by hbers** [z411/trackma#181]
Rescanning library used to find anime in every category but now it only detects the ones in the watching category. When I first noticed it I thought that it was intentional. If that's not the case can you add an option to scan for all categories?

**Comment by z411** [comment]
It is indeed intentional, since rescanning the whole list, especially if you have a lot of completed shows, takes more time, and I assumed that it shouldn't be necessary to scan for shows in the Completed list. Maybe scan for all shows except completed (since it tends to be the largest)?

**Comment by hbers** [comment]
Yeah that's more practical definitely. Additionally I think there is no need for scanning Dropped too.

**Comment by Fasolt** [comment]
I'd like to second this request, as it'd helpful to be able to just pick an anime from my PTW and click on Play Next, with everything working automatically. Perhaps it would be possible to add an option in config.json for choosing which list sections the user would like scanned; that way, people who don't want the broadened library scan won't suffer a performance drop.
Otherwise, simply scanning Watching, PTW and possibly On Hold would be sufficient, I imagine.

**Comment by MadeOfMagicAndWires** [comment]
I have roughly implemented this, optimising out Dropped however would require more rigorous optimization however, so I'd like some user input on how big people's Dropped lists tend to be (and if you keep the files) to see if that's worth it before filing a PR.

I'd probably recommend keeping this setting off regardless though, since a library scan went from just over 2 seconds to ~30+, and that is *without* Completed shows.

**Comment by hbers** [comment]
Why not just scan the PTW and Watching then? There's no need to scan for Dropped and Watched in my opinion. It's not like people don't know what they've watched and what is on their drives.

**Comment by z411** [comment]
He did say
> and that is without Completed shows
which is weird, unless you have a lot of shows on hold/dropped/PTW.

**Comment by MadeOfMagicAndWires** [comment]
I have 11 shows for On-hold (no files of dropped series, for obvious reasons) not sure if that's a lot, but the main killer for me is there's quite a lot files ( several series with 50+ episodes) and some large files as well in between those shows that take quite a bit of time to process. 

But that's just one case, so I'm trying to figure out if optimizing Dropped out dropped is even worth it. 

The problem with scanning for PTW and Watching as @hbers suggests is that the current data model doesn't keep track of what status is PTW, so we can't specifically scan for it. 
The current model only keeps track of "Watching" and "Completed" as specific statuses because we can be fairly certain those statuses will exist across all services, so currently I scan for everything *except* completed.

It'd be pretty easy to specify each status though, and just check for 0 if any api doesn't have a PTW status, we could use 0 if we come across a service that doesn't have such a status, but before touching the data model I'd like to see if it's even needed.

If anyone wants to try it out, it's over [here](https://github.com/MadeOfMagicAndWires/trackma/tree/lib-scan-whole-list). Be sure to enable it in the settings menu of either GUI and let me know if there's any significant change when scanning.

**Comment by Birdulon** [comment]
I think 30+ second scans wouldn't be much of a problem if they didn't disable the GUI for the duration. Is there a reason for the `_busy()` call in the first place?

**Comment by z411** [comment]
Indeed I think we can safely remove the `_busy()` call. But still 30 seconds sounds like a lot, it might be better to find a way to optimize the algorithm. If I remember correctly Taiga was pretty fast and it scanned the whole list I think.

**Comment by MadeOfMagicAndWires** [comment]
This can be closed.
