### ISSUE TITLE
Command Line Interface - Reshow prompt after output

### ISSUE THREAD

**Issue by Euren** [z411/trackma#209]
When using the command line interface, the prompt is not shown again after messages about the player. So you end up with
`
[mal] (anime) watching >> Tracker warning: Player is not playing the next episode of Anime Name. Ignoring.`

when you'd like

`[mal] (anime) watching >> Tracker warning: Player is not playing the next episode of Anime Name. Ignoring.`
`[mal] (anime) watching >>`

**Comment by MadeOfMagicAndWires** [comment]
I've looked into this, and it's more a problem of the `cmd` module not realising it needs to redraw the prompt without user input. It's very hard to trigger that from our side, especially because we don't want to redraw the prompt *every* time a message is printed.

So short of writing a whole new CLI lib I don't think we can do much about this, maybe pass it on to whoever maintains `cmd` but it's a very specific thing that even for trackma only goes wrong *some* of the time, so I think it's just something we'll have to live with.

**Comment by z411** [comment]
It seems the readline module has the `get_line_buffer` function, which would actually help to do it ourselves. We could clear the line with a carriage return, show the message, then rewrite the buffer.

**Comment by z411** [comment]
I think that commit does it, please check if it works.

**Comment by MadeOfMagicAndWires** [comment]
Does indeed work. That's a lot easier than I expected it to be, good job!

**Comment by z411** [comment]
Neat. Will mark as fixed.
