### ISSUE TITLE
anidb.net support

### ISSUE THREAD

**Issue by soredake** [z411/trackma#215]

**Comment by zJoul** [comment]
I'll try to look into this, but for the moment, the anidb wiki is down and I don't have a clue about the API

**Comment by rr-** [comment]
IIRC their API is very unfriendly and has lots of quota-based limitations :-1:

**Comment by z411** [comment]
It is, I was in route to implementing the TCP API but most functionality had nothing to do with what Trackma does either way.

**Comment by z411** [comment]
The wiki is now up. Probably what's relevant to us are the MyList commands, but they seem to be centered around files, not shows.

http://wiki.anidb.info/w/UDP_API_Definition#MyList_Commands

**Comment by MadeOfMagicAndWires** [comment]
I've looked into this a bit, and for proper functionality we'd need to use at least both the UDP and HTTP API. 
The UDP API doesn't allow for retrieving of entire lists and the HTTP one only allows for very basic,static lists so we'd end up having to first fetch and parse an xml file through HTTP, and then use the UDP API if we want to alter that list.
To top it off if we'd want to *search* anidb we'd have to either store and parse a title to id file locally or use a [third party service](http://anisearch.outrance.pl/). 

So it's doable, but a lot more work than most APIs. I was thinking of maybe working on this, but I figure we'd first want to decide whether it's worth the hassle, especially concerning the locally storing of their entire database.

**Comment by rr-** [comment]
Random internet anon (me) is against this, if they work so hard to make it hard for the API consumers, then let them win and move to competition

**Comment by z411** [comment]
Same. Anidb's API is pretty old, from before having personal lists was a thing, so it's not really designed for that. I don't think many people use Anidb for that either way; and their own clients do things other than just keeping a list with score and status.

**Comment by MadeOfMagicAndWires** [comment]
:+1:

**Comment by Birdulon** [comment]
They have nice info to draw from that isn't readily available on
MAL/Anilist (releases) so I can see why people would want it. With the API
being such a pain, may as well leave it to any contributors who feel up to
it.
On 26/10/2016 9:53 am, "z411" <notifications@github.com> wrote:

Same. Anidb's API is pretty old, from before having personal lists was a
thing, so it's not really designed for that. I don't think many people use
Anidb for that either way; and their own clients do things other than just
keeping a list with score and status.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/z411/trackma/issues/215#issuecomment-256207727>, or mute
the thread

**Comment by MadeOfMagicAndWires** [comment]
The problem with that nice info though is that currently Trackma doesn't have the tools to support it, and as you said it isn't available for MAL, so it isn't supported there either,l. Any implementation of the anidb features could not be used for other APIs and are too widespread to fit in just the API library file.




-- 
"We apologize for the inconvenience"

**Comment by MadeOfMagicAndWires** [comment]
Forgot to mention this: should anyone want to try their hand at it, I already registered trackma as an API client to test things out, so please [contact me](mailto:toost.b@gmail.com) for the details.
