### ISSUE TITLE
Autosend error

### ISSUE THREAD

**Issue by giuliandenicola** [z411/trackma#245]
When **auto-send**  after every change
is used it will freeze at **libmal: Updating show ...**
But when **send changes (CTRL+E)** is used then it will work fine

**EDIT:**
It does updates the list, but freezes afterwards.

trackma-gtk often closes by itself with log:
`[4]+  Killed                  trackma-gtk`
`Segmentation fault (core dumped)`

Also my console is being spammed with this error, every couple of seconds.
`Isof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.`

**Comment by underr** [comment]
I'm having this problem as well, same error message and everything.

**Comment by z411** [comment]
I can't seem to reproduce the problem. Does this happen with the other interfaces?

The lsof warning can be safely ignored.

**Comment by giuliandenicola** [comment]
No it doesn't, only on the GTK version.
The **libmal: Updating show ...** at **autosend** does happen on all interfaces.

**Comment by Fasolt** [comment]
I'm also getting crashes in the GTK version. From what I've been able to tell, the crashes occur when the tracker tries to update the start or end date of a show. The crash doesn't take place if you manually click on the + button to increase episode count and thereby change the start or end date where applicable; it only happens when the tracker automatically updates the show's start or end date. The crash occurs at some point between setting the status of the show (e.g. going from 'Plan to Watch' to 'Watching', or from 'Watching' to 'Completed'), which is successful, and setting the start or end date, which is unsuccessful. This only happens in the GTK version: the QT version runs smoothly. Below is the terminal output for both GTK (crash) and QT (successful); I tried running the program with flags like '-v' and '--verbose', but that doesn't seem to have an effect. If you can let me know how to increase error logging or verbosity, that might be helpful in diagnosing the problem.
GTK crash output:
`Engine: Updating show Tari Tari to episode 13...
Data: Saving queue...
Data: Saving cache...
Data: Queued update for Tari Tari
Data: Processing queue...
libmal: Updating show Tari Tari...
Data: Saving cache...
Data: Saving queue...
Engine: Updating show Tari Tari status to Completed...
Data: Saving queue...
(trackma-gtk:15191): Gtk-WARNING **: Allocating size to GtkWindow 0x18d6270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Data: Saving cache...
Data: Queued update for Tari Tari
Data: Processing queue...
libmal: Updating show Tari Tari...
Data: Saving cache...
Data: Saving queue...
Segmentation fault (core dumped)`
QT success output:
`Engine: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari to episode 1...
Data: Saving queue...
Data: Saving cache...
Data: Queued update for Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari
Data: Processing queue...
libmal: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari...
Data: Saving cache...
Data: Saving queue...
Engine: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari status to Completed...
Data: Saving queue...
Data: Saving cache...
Data: Queued update for Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari
Data: Processing queue...
libmal: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari...
Data: Saving cache...
Data: Saving queue...
Data: Saving queue...
Data: Saving cache...
Data: Queued update for Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari
Data: Processing queue...
libmal: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari...
Data: Saving cache...
Data: Saving queue...
Data: Saving queue...
Data: Saving cache...
Data: Queued update for Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari
Data: Processing queue...
libmal: Updating show Tari Tari: Kumottari, Kagayaitari, Mata Itsuka Utattari...
Data: Saving cache...
Data: Saving queue...`

**Comment by Birdulon** [comment]
Can reproduce on my (admittedly broken) end. The problem appears to occur on `self.store.clear()` in `append_start`. Won't give line numbers as mine are a bit offset by debug calls.

**Comment by z411** [comment]
The threading usage in the GTK interface is (admittely) kind of clunky, it might need a rewrite but I haven't touched GTK 3 in months since I don't have it installed at all. It seems this specific issue started happening after switching to GTK 3.

The tracker is in a worker thread in the Qt interface, but it doesn't work like that in the GTK one; the engine is in the main thread it just runs in a separate thread when starting a time-consuming task (task_* functions). The tracker is always in a separate thread though, which might definitely be what is causing the issue.

**Comment by z411** [comment]
I can't seem to reproduce the problem; could anyone send me your config.json to try it under the same configuration?

**Comment by z411** [comment]
Made a quick change that should fix threading problems; please pull the latest commit and check if the problem persists.

**Comment by Birdulon** [comment]
0f8fd1c has fixed it on my end.

**Comment by Fasolt** [comment]
Glad to report that you've managed to fix it for me as well; thanks for handling it so quickly!
Presumably you no longer need the config.json file, but just in case:
```
{
    "auto_date_change": true,
    "auto_status_change": true,
    "auto_status_change_if_scored": false,
    "autoretrieve": "always",
    "autoretrieve_days": 3,
    "autosend": "always",
    "autosend_at_exit": true,
    "autosend_hours": 5,
    "autosend_size": 5,
    "debug_disable_lock": true,
    "library_autoscan": true,
    "player": "mpv -fs",
    "plex_host": "localhost",
    "plex_port": "32400",
    "searchdir": "/home/your_name_here/anime",
    "tracker_enabled": true,
    "tracker_interval": 180,
    "tracker_process": "mpv",
    "tracker_type": "local",
    "tracker_update_close": false,
    "tracker_update_prompt": false,
    "tracker_update_wait_s": 1080
}
```

**Comment by z411** [comment]
Good to know, thanks for reporting.
