### ISSUE TITLE
[MAL] Unable to update, credential verification throwing 403 errors

### ISSUE THREAD

**Issue by matoro** [z411/trackma#252]
Exactly what it says in the title, I'm unable to push my local updates to MAL remote service because the credential verification API https://myanimelist.net/api/account/verify_credentials.xml is throwing a 403 forbidden.  I am able to access it in my browser as well as via curl, so it must be a trackma problem.  I don't know enough python to look into the request bodies, I was only able to pick up this much using the ```httpry``` logger.  Here's the full log output of a request:

```
httpry version 0.1.8 -- HTTP logging and information retrieval tool
Copyright (c) 2005-2014 Jason Bittel <jason.bittel@gmail.com>
Starting capture on enp0s20u1u4 interface
2016-11-01 17:31:51	[redacted]	54.71.215.176	>	GET	myanimelist.net	/api/account/verify_credentials.xml	HTTP/1.1	-	-
2016-11-01 17:31:51	54.71.215.176	[redacted]	<	-	-	-	HTTP/1.1	403	Forbidden
```

where the destination IP 54.71.215.176 is one of MAL's AWS instances (I've redacted my own IP).  I can provide further information if needed.

**Comment by z411** [comment]
I'm assuming MAL is now forcing HTTPS. Trackma just started using HTTPS for everything; did you try getting the latest master through git?

**Comment by matoro** [comment]
That might be the issue.  I'd prefer not to mess up package managers though so could you either bump Arch Linux AUR version or push to pypi?

**Comment by z411** [comment]
Sure, I can push to pypi.

I'm not the AUR maintainer but I assumed the PKGBUILD was pulling from the latest git?

**Comment by matoro** [comment]
Just tested it, rebuilding package does fix the issue.  The problem is that most AUR wrappers (yaourt, pacaur, etc.) will only rebuild a package they register as "updated," which means a version bump.  So it only gets rebuilt when the script version is updated.  The maintainer is probably subscribed to the release feed for this repo, so if it's not a new formal release, they won't be notified.  Small fixes like this that can be potentially functionality-breaking might warrant a small release, either that or some way of notifying package maintainers when something important like this gets added.

**Comment by z411** [comment]
I'll use the opportunity to craft a new release; the HTTPS change indeed is important enough.

**Comment by MadeOfMagicAndWires** [comment]
I am indeed subscribed :crystal_ball:. 

The issue with these git tracking packages is indeed that because it simply grand the latest commit the package version number is actually built when makepkg is run, but this isn't reflected the static PKGBUILD And .SRCINFO file where the version number has to be updated manually. 

I usually do this every release, or on a major bugfix that affects Arch Linux (as well) but generally with -git packages it's good to manually repackage them every once in a while as well, especially when they break.

@z411 bit late but Trackma doesn't use HTTPS on *all* sites, just those that support it. I believe it was Melative and Shikimori that still use plain HTTP because they don't provide an HTTPS connection.
