### ISSUE TITLE
Tracker fails to update anime episodes (pyinotify)

### ISSUE THREAD

**Issue by 4re** [z411/trackma#255]
Lately trackma-qt 1c6ebd84e1944e674ab3d99060421904a72df2aa (python-3.5) is not able to update the shows.

Here is a little log with the update interval reduced to 10 seconds to show you the problem: http://pastebin.com/raw/6F0w19uX

EDIT: I retract myself, the this was not happening before... don't know why it can be happening now.

**Comment by z411** [comment]
Will try to reproduce it. As an aside, does the library message always appear that many times?

**Comment by Birdulon** [comment]
I've noticed strange behaviour with the tracker update_show_if_needed logic as well since I started messing around with it (which may well be the fault of my additions). Never managed to reproduce any of it though.
I'm currently refactoring it and should have a PR up in several hours.

**Comment by z411** [comment]
@Birdulon This shouldn't be affecting the update function, but should the pyinotify event handler be emitting a `detected` signal for IN_OPEN and IN_CLOSE? It's attempting to add the show to the library every time. Or is this intentional?

**Comment by Birdulon** [comment]
@z411 It's congruent with the inotify event handler's behaviour of detect everything that isn't a `removed`. It might be a bit overkill detecting on close when it detects on open, and the `detected` messages are certainly polluting the log as-is. I suppose it's a question of whether to suppress the log messages or make the detection less eager, and if so, just how much detection is enough to ensure all edge cases are covered (e.g. Trackma opened after file is opened, or Trackma closed before file is closed) so that the library doesn't miss anything, without going overboard.

I noticed that the tracker's `_get_playing_show` returns a state of `4` if the filename is the same as the last filename. Is there any significance to this? If so, I'll give it a name like `STATE_REPEATED` otherwise I'll replace it with the last state.

**Comment by z411** [comment]
Returning last state should be prudent.

**Comment by 4re** [comment]
I'm having the same problem after the update, but now no python error is shown when the show fails to update.

I checked commit history to find the one at fault and it was e63c6dc6c9bfe9865c55cb55e5771494505c7e38, before this commit no problems at all.

**Comment by 4re** [comment]
Hurray, latest pull request from @Birdulon fixed it! Thankyou guys.
