### ISSUE TITLE
Player not found check your config.json

### ISSUE THREAD

**Issue by ghost** [z411/trackma#319]
I'm getting this. Doesn't matter what player I use. It still doesn't open the player. But if I open an episode manually it will update the episode. I'm on updated Arch Linux with kernel 4.14.3, and I'm using trackma-gtk.

**Comment by Ashymad** [comment]
Sometimes trackma forgets my player as well. You just have to open ~/.trackma/config.json and type your player name in the player field. e.g. "player": "mpv",

**Comment by okabekudo** [comment]
Oh... what a simple fix that was. I never saw that there was an extra entry for player... I always assumed it was the tracker_process... Either way that should be considered a bug shouldn't it?

**Comment by z411** [comment]
They are two separate options, yes. If you're using the Qt or GTK interfaces you can see them both in separate sections in the Settings dialog.

`player` (Player) is the path to the player when you whan to use Trackma to start it (with the Play Next button), while `tracker_process` is actually a **regex** for the tracker to check whether a process playing a video is a video player or not.

I guess we could merge these into one option, but some people might be using the regex features of the `tracker_process` setting to match multiple video players and just removing it would be disrespectful in that case.

What **shouldn't** happen though, is what @Ashymad says about Trackma *forgetting* the player. Could you give some details about this?

**Comment by Ashymad** [comment]
I do not remember doing anything special that could have caused this, I just opened trackma as always and it threw the "player not found" message. However, because it has happened only about 3 or 4 times in the span of half a year I did not care enough to try to find out what has caused this behaviour. Sorry to be of no help.

**Comment by okabekudo** [comment]
> I guess we could merge these into one option

No it's totally okay the way it is. I just never saw that there was a player option in the config.json file because I assumed it was the `tracker_process` entry that caused the "player not found" message because well I didn't bother reading through the config.json file because it didn't bother me enough. But yes trackma must have deleted my `player` entry aswell because I even deleted the app and all it's config directories, but it still gave me the error (until I fixed the `player` entry ofc). But I can't recreate the steps that led to trackma deleting that entry.

**Comment by FichteFoll** [comment]
I'm not seeing the mentioned second input field for the `player` setting.

![2018-03-13_04-05-00](https://user-images.githubusercontent.com/931051/37320403-df87ab78-2673-11e8-883d-58f516cb7cb6.png)

The other two tabs don't have any text inputs at all.
