### ISSUE TITLE
Respect XDG config directory conventions

### ISSUE THREAD

**Issue by kutsan** [z411/trackma#352]
Currently, config files read from `~/.trackma` directory, it also should look for `~/.config/trackma` folder or XDG environment variables.

**Comment by rr-** [comment]
There's module for this on PIP: https://pypi.org/project/xdg/ which should make developing this feature easier.

**Comment by kutsan** [comment]
@rr- It's super easy to implement on your own. No need to create extra complexity IMO.

**Comment by rr-** [comment]
It's also super tiresome to repeat those few lines in every open source project you maintain. (I'm using this module in about 10 projects)

**Comment by kutsan** [comment]
@rr- In my opinion, some decisions in software world are developer-friendly and other things are user-friendly. Using a module may be developer friendly for you but some random user in future probably get an error about required dependency.

I think, a great example would be Electron itself. It's insanely developer-friendly since there is no learning curve involved but heavy memory usage is not a good thing at all for users.

That said, I don't mind both ways; the maintainer can decide the way to go.

**Comment by z411** [comment]
I'm personally not a fan of anything related to the Freedesktop project, but I think the XDG directory standard is sane enough to implement as $HOME clutter is certainly an issue.

Regarding this discussion, most of the time I try to get rid of dependencies as much as I can; Trackma CLI can run properly without any dependency, so I'd prefer not to add any, especially since this isn't hard to implement.

It's mostly an issue of design, not implementation. There are a few things that have to be re-thought.

- Currently everything is thrown into `~/.trackma` but this would mean we would have to separate configs (config*.json), data files (account directories, account dictionary) and cache (GUI clients cache, mostly images). There's also an info cache kept into account directories (show details basically), should we treat these as data files or should we put these into the cache directory instead? Doing the latter would certainly change how things are stored currently.
- Trackma is not a Linux only program so this would mean we have to implement platform-specific config directory guessing as well, besides the XDG one. In Windows it would be %APPDATA% and I'm still not sure how BSD or BSD-like Linux distros like CRUX or Alpine handle XDG yet. It is also a terminal program originally; the desktop GUIs were implemented as addons.
- Backward compatibility; we have to make sure it still tries to look into `~/.trackma`.

**Comment by kutsan** [comment]
> Currently everything is thrown into ~/.trackma but this would mean we would have to separate configs (config*.json), data files (account directories, account dictionary) and cache (GUI clients cache, mostly images).

I think they need to be separated. They are not human-readable, so there is no reason to keep them under config directories `~/.trackma/` and `~/.config/trackma/`.

> should we treat these as data files or should we put these into the cache directory instead? Doing the latter would certainly change how things are stored currently.

I think trackma should put them into cache directory.

> Backward compatibility; we have to make sure it still tries to look into ~/.trackma.

I agree.

**Comment by z411** [comment]
Implemented in the `develop` branch.
