### ISSUE TITLE
QT interface not working trackma.utils

### ISSUE THREAD

**Issue by ardydo** [z411/trackma#418]
I just updated trackma from 0.7.6 to 0.8.1 using pip on my kubuntu installation. Everything was working just fine before but when I try to start either the QT or QT4 interface it won't start and this error comes up.

> Trackma-qt v0.8.1
> Traceback (most recent call last):
>   File "/usr/local/bin/trackma-qt4", line 11, in <module> sys.exit(main())
>   File "/home/ardydo/.local/lib/python3.6/site-packages/trackma/ui/qt4ui.py", line 22, in main qtui.main()
>   File "/home/ardydo/.local/lib/python3.6/site-packages/trackma/ui/qtui.py", line 3271, in main mainwindow = Trackma(debug)
>   File "/home/ardydo/.local/lib/python3.6/site-packages/trackma/ui/qtui.py", line 122, in __init__ self.configfile = utils.get_root_filename('ui-qt.json')
> AttributeError: module 'trackma.utils' has no attribute 'get_root_filename'

Other interfaces are working fine

I tried reinstalling it (also using pip) but also to no avail

**Comment by z411** [comment]
Hello, thanks for reporting.

It seems that for some reason you have leftovers of a previous Trackma version because `get_root_filename` has been removed long ago and the file `trackma/ui/qtui.py` shouldn't exist at all. What command exactly are you using to install Trackma, and are you doing it as user or as root?

It also seems that the binary is in a system directory, but the module is in your home directory. It could be a mix up of a root install and a home install. Try running `pip3 uninstall trackma` twice both as root and as user, then run `pip3 install trackma` again as user only. The `trackma-qt` binary should be in `/home/ardydo/.local/bin`, not `/usr/local/bin`.

**Comment by ardydo** [comment]
Hey, thanks for the reply!

I'm not sure what I did that my installation ended like this but I actually had two conflicting installations of trackma and one updated while the other got stuck in 0.7.6. What actually fixed my problem was:

1. running pip3 uninstall trackma which removed the normal installation
2. running sudo -H pip3 uninstall trackma to remove the installation in /usr/local/bin that shouldn't be there. This showed that the old version was uninstalled
3. finally runing sudo pip3 install trackma to reinstall trackma on /home/ardydo/.local/bin.

Running it without sudo while did put the files on the right place but wasn't making the commands work (trackma, trakma-qt, etc. was showing as "not found"). I could click the files and the program would run but not from terminal etc. but when I added sudo it installed in the right location and then registered the commands just fine.

Thanks again for the help (and the awesome program).
