### ISSUE TITLE
[Config] Use yaml or toml instead of json for config files.

### ISSUE THREAD

**Issue by ahmubashshir** [z411/trackma#543]
Both YAML and toml are easier to write and more human readable than json. So, we should use toml or yaml instead of json :3

**Comment by molkoback** [comment]
Qt and GTK interfaces will overwrite your neatly formatted and commented yaml/toml config files. On the other hand, the GUI users probably won't be manually editing their config files anyway.

**Comment by FichteFoll** [comment]
The JSON file is quite small and not deeply nested, meaning it is quite easy to edit by a human. YAML would be overkill and both are prone to modifications that would rearrange settings on every change by the program itself. `ruamel.yaml` has a roundtrip parser that can preserve original structure, but that's still way overkill. Using JSON for this is perfectly fine, especially since it's part of the stdlib.

**Comment by ahmubashshir** [comment]
ok then... I'll close this :3
