### ISSUE TITLE
Anilist - Invalid HTTP Request

### ISSUE THREAD

**Issue by Baa14453** [z411/trackma#577]
Tried Synchronising and Downloading my anilist today and recieved the below:
`Error: Invalid HTTP request: b'{"errors":[{"message":"Invalid token","status":400,"locations":[{"line":2,"column":3}]}],"data":{"MediaListCollection":null}}'`

Anime search doesn't work either.
`libanilist: Searching for Penguin Highway...
Invalid HTTP request: b'{"errors":[{"message":"Invalid token","status":400,"locations":[{"line":1,"column":44}]}],"data":{"Page":null}}'`

Trackma GTK v0.8.4
Using Ubuntu 20.04

**Comment by dnisyd** [comment]
Same with Trackma-curses on ArchLinux 5.14.2-arch1-2

**Comment by coolboymew2** [comment]
I suspect that Anilist is having API issues

Started a month or two ago. Sending changes takes forever sometimes and the program seems to crash sometimes while sending updates while I'm watching an episode

It went away for awhile and it seems back now. I don't know why exactly, but maybe trackma has issues with timeout or something. The issue is especially irritating because if I have to manually update something, trackma is entirely locked during the update which can take up to 30 secs now

**Comment by z411** [comment]
Is this still an issue? If so we should definitely lower the timeout value. 30 seconds is indeed a lot.

**Comment by Baa14453** [comment]
Sorry, after re-adding my account Trackma started working fine again, I'm not sure what happened exactly.
If it happens again I'll re-open this.

**Comment by coolboymew2** [comment]
Haven't been an issue for a while
