### ISSUE TITLE
Single CLI Commands

### ISSUE THREAD

**Issue by noctuid** [z411/trackma#79]
Would there be any possibility of adding support for single wmal commands (e.g. something like `wmal search <title>` or `wmal-cli -a 1 search <title>` if an account needed to be specified)  that would print the results or take the action and then return to the shell and not a wmal prompt? 

I don't really find the curses interface useable (due to the lack of customizable bindings among other things), and would much prefer having no interface, so I that could combine commands with shell scripting (e.g. if I wanted to parse output or send it to a file easily or evaluate something $(...) in a wmal command) and keep my shell key bindings.

**Comment by SleepyMan** [comment]
If it is a daemon, it would make sense to auto-add shows that are not in our lists, as we won't be able to use the season browser/search effectively to add shows (right-click -> add).
I understand that this would lead to fuzzy matches, etc. But we could start with perfect matches only at first.

Sorry if this is already implemented. Haven't used wmal/trackma since Oct.

**Comment by rr-** [comment]
Personally I'd like to run `trackma-cli update PATH.mkv` (plus all the necessary `--user rr- --account mal`) so that it runs its title/episode detection and syncs changes to MAL - the reason being I already use my own file tracker.

**Comment by z411** [comment]
After **quite a bit** of time I'm revisiting this issue since I've been getting requests for it.

@rr-: Trackma isn't designed to load more than 1 account at a time; the quickest way to do this is to have the current Trackma CLI module start up Trackma with the selected account, run the command, and then close. It takes a bit to start up (around ~500ms) due to module importing mostly.

As a daemon it could technically open several Trackma instances internally (thus a tracker instance for each account as well), but it might be a bit hackish, and I'm not sure how GUI interfaces can handle this.

**Comment by z411** [comment]
Definitey late but following @rr-'s idea I implemented single commands in the CLI interface. You can set the account number with -a (otherwise it'll use the default one, if set), run the command, and exit.

For example, if a default account is set:

```
$ trackma ls
$ trackma update 4
$ trackma send
```

or
```
$ trackma update file:PATH.mkv
```

should work. If you want to use a specific account:

```
$ trackma -a4 retrieve
```

When run in this mode it'll skip some time-consuming operations by default (library scan, tracker initialization, hook importing) so the command can run relatively quickly. If no command is specified then it'll run in the regular interactive mode. I should definitely document this.

**Comment by z411** [comment]
Done. This should work:

```
echo -e "retrieve\nls" | trackma -a6 -
```
