### ISSUE TITLE
Qt: Remember last window size and position

### ISSUE THREAD

**Issue by veluria** [z411/trackma#88]
Every time you close Trackma to the tray and re-open it, it will always use its default size and the default position assigned by the window manager. While the positioning of the window is debatable, I think it should at least memorize the size. 

The GTK interface remembers both, although I didn't check whether you implemented this or if this is just the default behaviour of GTK. 

Both of them do use the default size again upon really closing them, though.

**Comment by z411** [comment]
Thank you; I'm aware of this as it has been reported here #54

**Comment by z411** [comment]
Thank you; I'm aware of this as it has been reported here #54 
It is indeed both Qt's and GTK's default behavior. I don't know how GTK does it but this seems to be an X11 specific issue.

https://stackoverflow.com/questions/13462119/pyqt4-window-shows-up-at-another-position-after-hide-and-show

Since this is pretty annoying I guess I'll end up implementing whatever hack is needed.

**Comment by veluria** [comment]
Ah, I'm sorry. I didn't realize there already was an issue reading this.
